version: '3.9'

services:
  controller-db:
    container_name: controller-db
    build:
      context: ./data
      dockerfile: Dockerfile
      args:
        - STARTUP_SCRIPTS_DIR=./scripts
    environment:
      - POSTGRES_USER=java
      - POSTGRES_PASSWORD=java
      - POSTGRES_DB=deployment_controller
      - PGDATA=/var/lib/postgresql/data
    networks:
      - net-controller-backend
    volumes:
      - vol-controller-data:/var/lib/postgresql/data

  controller-backend:
    container_name: controller-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - SERVER_PORT=8181
      - DB_CONNECTION_URL=jdbc:postgresql://controller-db:5432/deployment_controller
      - DB_CONNECTION_USERNAME=java
      - DB_CONNECTION_PASSWORD=java
      - APP_SECURITY_DOMAIN=localhost
      - APP_SECURITY_FRONTEND=http://localhost
      - APP_SECURITY_KEY=c29tZS1rZXk=
      - APP_SECURITY_TOKEN_EXPIRE_HOURS=168
      - APP_SECURITY_DEFAULT_MAIL=root@test.com
      - APP_SECURITY_DEFAULT_PASSWORD=root
    depends_on:
      - controller-db
    networks:
      - net-controller-backend
      - net-controller-public

  controller-proxy:
    container_name: controller-proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - controller-backend
    tty: true
    networks:
      - net-controller-public

networks:
  net-controller-backend:
  net-controller-public:

volumes:
  vol-controller-data: