version: '3.9'

services:
  controller-db:
    container_name: controller-db
    build:
      context: ./data
      dockerfile: Dockerfile
      args:
        - STARTUP_SCRIPTS_DIR=./scripts
    environment:
      - POSTGRES_USER=java
      - POSTGRES_PASSWORD=java
      - POSTGRES_DB=deployment_controller
      - PGDATA=/var/lib/postgresql/data
    networks:
      - net-controller-backend
    volumes:
      - vol-controller-data:/var/lib/postgresql/data

  controller-backend:
    container_name: controller-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - SERVER_PORT=8181
      - DB_CONNECTION_URL=jdbc:postgresql://controller-db:5432/deployment_controller
      - DB_CONNECTION_USERNAME=java
      - DB_CONNECTION_PASSWORD=java
      - APP_SECURITY_KEY=c29tZS1rZXk=
      - APP_SECURITY_TOKEN_EXPIRE_HOURS=168
      - APP_SECURITY_DEFAULT_MAIL=root@test.com
      - APP_SECURITY_DEFAULT_PASSWORD=root
    depends_on:
      - controller-db
    networks:
      - net-controller-backend
      - net-controller-public

  controller-proxy:
    container_name: controller-proxy
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - controller-backend
    tty: true
    networks:
      - net-controller-public
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/mime.types:/etc/nginx/mime.types
      - ./proxy/test-automation.html:/pages/automation/index.html
      - ./proxy/test-portfolio.html:/pages/portfolio/index.html
      - ./proxy/test-overview.html:/pages/overview/index.html
      - ./proxy/test-login.html:/pages/login/index.html

networks:
  net-controller-backend:
  net-controller-public:

volumes:
  vol-controller-data: