host: 0.0.0.0
port: 8080
cache_type: local
db:
  name: deployment_controller
  host: docker.for.mac.localhost
  port: 5432
  user: postgres
  password: postgres
jwt:
  secret: ZG9uJ3QgZG8gdGhpcw==
  lifetime: 168 #hous
  domain: localhost
root:
  mail: test@mail.com
  password: test
mail:
  sender: noreply-deployments@michu-tech.com
  receiver: admin@michu-tech.com
  max_count: 5
  count_duration: 10
  smtp:
    host:
    port:
    user:
    password:
  max_message_length: 1000
cors:
  origins: https://host.michu-tech.com,http://host.michu-tech-dev.net,http://localhost
totp:
  totp_lifetime: 30 # seconds
  slow_totp_lifetime: 300 # seconds
location:
  host:
  account:
  license:
  cache_expire_hours: 48
  check_wait_time_minutes: 2
  local_ip:
log:
  level: 5 # logrus debug
  file_name: /var/log/deploy-ctl/backend.log