server:
  port: 8181
  host: 0.0.0.0

app:
  security:
    key: c29tZS1rZXk=
    tokenExpireHours: 168
    default:
      mail: admin@test.com
      password: admin

db:
  source: jdbc
  connection:
    url: jdbc:postgresql://localhost:5432/deployment_controller
    username: java
    password: java
    poolName: postgresql
    initializationFailTimeout: -1
    connectionTimeout: 2000
  statements:
    select-user: "select * from users where id = :id"
    select-user-mail: "select * from users where mail = :mail"
    select-users: "select * from users"
    insert-user: "insert into users (mail, password, salt, admin, view_private) values (:mail, :password, :salt, :admin, :view_private)"
    update-user: "update users set mail = :mail, password = :password, admin = :admin, view_private = :view_private where id = :id"
    delete-user: "delete from users where id = :id"
    select-page: "select * from pages where id = :id"
    select-pages: "select * from pages"
    insert-page: "insert into pages (url, title, description, private_access) values (:url, :title, :description, :private_access)"
    update-page: "update pages set url = :url, title = :title, description = :description, private_access = :private_access where id = :id"
    delete-page: "delete from pages where id = :id"
    mark-login: "update users set last_login = :last_login where id = :id"

