server:
  port: 8181
  host: 0.0.0.0

app:
  security:
    frontend: "*"
    domain: "localhost"
    key: c29tZS1rZXk=
    tokenExpireHours: 168
    default:
      admin: admin@test.com
      mail: admin@test.com
      password: admin
    mail:
      from: admin@test.com
      password: admin
      smtp:
        user: smtp-relay@admin.com
        password: smtp-relay-admin-password
        port: 22
        server: ssl.mail.com
  logs:
    directory: "./logs"
  location:
    host: geolite.info
    account: 873989
    license: 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
    cacheExpireHours: 48

db:
  source: jdbc
  connection:
    url: jdbc:postgresql://localhost:5432/deployment_controller
    username: java
    password: java
