version: '3.9'
name: dev_deployment_controller

services:
  proxy:
    container_name: deployment_controller_dev_proxy
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: no
    tty: true

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.0.0
    container_name: deployment_controller_dev_filebeat
    user: root
    command: > 
      filebeat 
        -e --strict.perms=false
    volumes:
      - ./backend-filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./backend-filebeat/data:/usr/share/filebeat/data:rw
      - ./backend-filebeat/backend-log.json:/var/log/deployctl/log.json
      - ./ekl-certs/ca.crt:/etc/elasticsearch/certs/ca.crt:ro